/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Uber.CarInfo;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Samruddhi
 */
public class UserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserJPanel
     */
    private CarInfo carInfo;
    private JPanel rightPanel;
    public UserJPanel(JPanel rightPanel, CarInfo carInfo) {
        initComponents();
        this.rightPanel = rightPanel;
        this.carInfo = carInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLooking = new javax.swing.JButton();

        btnLooking.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLooking.setText("Looking for an Uber?");
        btnLooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(btnLooking, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(btnLooking, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookingActionPerformed
        // TODO add your handling code here:
        SearchCarJPanel searchPanel = new SearchCarJPanel(this.rightPanel, carInfo);
        this.rightPanel.add("SearchCarJPanel", searchPanel);
        CardLayout layout = (CardLayout) this.rightPanel.getLayout();
        layout.next(this.rightPanel);
    }//GEN-LAST:event_btnLookingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLooking;
    // End of variables declaration//GEN-END:variables
}
